server {
    listen 80;
    listen [::]:80;

    root /usr/share/nginx/html;
    index index.html;

    add_header 'Referrer-Policy' 'no-referrer';
    add_header 'Cross-Origin-Opener-Policy' 'same-origin-allow-popups';

    location / {
        try_files $uri $uri/ /index.html;
    }
    location /api/ {
        proxy_pass http://back:5000;
    }
}