name: test and build

on: 
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled
    
jobs:
  validate_label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: check and validate PR label
        run: |
          LABELS="${{ join(github.event.pull_request.labels.*.name, ' ') }}"

          COUNT=0

          if [[ "$LABELS" =~ (^| )major($| ) ]]; then
            COUNT=$((COUNT + 1))
          elif [[ "$LABELS" =~ (^| )minor($| ) ]]; then
            COUNT=$((COUNT + 1))
          elif [[ "$LABELS" =~ (^| )patch($| ) ]]; then
            COUNT=$((COUNT + 1))
          fi

          if [ "$COUNT" -ne 1 ]; then
            echo "PR must have exactly one of: major, minor, patch"
            exit 1
          fi


  setup_and_lint:
    runs-on: ubuntu-latest
    needs: validate_label
    strategy:
      matrix:
        node-version: [25]
    permissions:
      security-events: write
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 10.20.0

      - name: use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: install dependencies
        run: pnpm install

      - name: lint
        run: pnpm lint

  
  test_build:
    runs-on: ubuntu-latest
    needs: validate_label
    permissions:
      contents: read
    steps:
      - name: authenticate to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Test build
        uses: docker/build-push-action@v7
        with:
          platforms: linux/amd64,linux/arm64 
          push: false